/*
 * BusyDialog.java
 *
 * Created on March 27, 2009, 10:18 AM
 */

package ca.wlu.gisql.gui;

import javax.swing.JFrame;

public class BusyDialog extends javax.swing.JDialog {

	/** Creates new form BusyDialog */
	public BusyDialog(JFrame parent) {
		super(parent);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		progress = new javax.swing.JProgressBar();
		label = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("gisQL");
		setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
		setName("frameProgress");
		setResizable(false);

		progress.setIndeterminate(true);

		label.setText("Computing result set...");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																label,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																211,
																Short.MAX_VALUE)
														.addComponent(
																progress,
																javax.swing.GroupLayout.Alignment.TRAILING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																211,
																Short.MAX_VALUE))
										.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap().addComponent(
						label).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28,
						Short.MAX_VALUE).addComponent(progress,
						javax.swing.GroupLayout.PREFERRED_SIZE, 22,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel label;

	private javax.swing.JProgressBar progress;
	// End of variables declaration//GEN-END:variables

}
